#import "@preview/ilm:2.0.0": *

#set text(lang: "en")
#set page(margin: 2cm)
#let day = datetime.today()

#show: ilm.with(
  title: [Wissenschaftliches Arbeiten und Hypothesenbildung - Kursnotizbuch],
  authors: "Andreas Hofer",
  date: day,
  abstract: [])

+ Modern e-services are provided by networks of collaborating businesses. However, collaborators, and even customers, don't always behave as expected or agreed upon, and fraudsters attempt unfair exploitation, legally or illegally.Profitability assessments of e-services should therefore look beyond revenue streams and also consider threats to the financial sustainability of the service offering. More importantly, any such analysis should consider the business network in which the e-service is embedded. The $e^3$ value method is an established modeling and analysis method that allows enterprises to estimate the net value flows of a networked e-business. Recently, the method and its ontology have been extended to cover aspects related to risk, e.g., fraud. In this paper, we introduce four new software-enabled risk and sensitivity analyses, which build upon this extension. The techniques are quantitative and therefore support making motivated risk mitigation decisions. We illustrate them in the context of three realistic case studies.
 - Über Browzine und die Onlinebibliothek

+ The data analysis was conducted in three main phases. First, an Exploratory Factor Analysis (EFA) was applied to examine the underlying structure of the constructs and verify that the items loaded properly on their respective factors. After confirming the dimensionality of the constructs, the analysis proceeded with the PLS-SEM method, which is implemented in two steps: the analysis of the measurement model and the analysis of the structural model. First, the measurement properties of the first-order constructs were assessed because these constructs serve as a foundation for the second-order constructs (LARG paradigm, CSFs, and SSCP). Following this, the structural assessment was conducted. All outputs generated by the SPSS and SmartPLS software are available and can be shared for further reference.
 - Das Journal heißt Industrial Management & Data Systems

+ In einer zunehmend herausfordernden Geschäftsumgebung besteht für kleine und mittlere Business-to-Business Unternehmen die Herausforderung, ihre Geschäftsprozesse und die unternehmensweiten Anwendungssysteme entsprechend der Technologielandschaft anzupassen, um konkurrenzfähig zu bleiben. Der zielgerichtete Einsatz von Künstlicher Intelligenz birgt das Potenzial für Effizienzsteigerung und Unterstützung in verschiedenen Geschäftsbereichen, darunter auch Marketing und Vertrieb. Trotz der zunehmenden Bedeutung von Künstlicher Intelligenz bleibt der Einsatz in kleinen und mittleren Unternehmen oft zögerlich. Das Ziel dieser Studie ist die Herleitung eines ganzheitlichen Ansatzes für eine mit KI-Werkzeugen unterstützte Customer Journey. Diese Arbeit untersucht dafür speziell den potenziellen Einsatz von Künstlicher Intelligenz in der Kundenkommunikation von kleinen und mittleren Unternehmen im produzierenden B2B-Sektor. Basierend auf zehn leitfadenorientierten qualitativen Interviews mit Praktikern aus produzierenden B2B-KMU werden deren spezifische Herausforderungen in der Kundenkommunikation identifiziert und der Einsatz von KI als potenzielle Lösung geprüft. Die Ergebnisse zeigen, dass der Einsatz von KI in der Kundenkommunikation produzierender B2B-KMU Potenzial birgt, um bestehende Herausforderungen zu mindern, wobei die Einsatzmöglichkeiten je nach Datenverfügbarkeit variieren. Die vorliegende Arbeit trägt dazu bei, produzierenden B2B-KMU aufzuzeigen, wie sie Künstliche Intelligenz einsetzen können, um ihre Herausforderungen zu bewältigen und die Kundenkommunikation zu optimieren.
 - Über Springer Nature

+ #figure(
  image("assets/google_scholar.png"),
  caption: [
    Two Open Access articles from Google Scholar. The 2nd link only provides access to the Abstract
  ],
)

+ In den vergangenen Jahren haben sich die Rahmenbedingungen im Hochschulsektor bedingt durch bildungspolitische Entscheidungen wie auch den technologischen Fortschritt bedeutend verändert, weshalb sich die Hochschulen einem zunehmenden Wettbewerbsdruck ausgesetzt sehen.
 - 